# CLEANING GEOJSON FILE

In [1]:
import pandas as pd
import geopandas as gpd

In [3]:
gdf = gpd.read_file('ntt.geojson')
gdf.head()

,GID_2,GID_0,COUNTRY,GID_1,NAME_1,NL_NAME_1,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,geometry
0,IDN.21.1_1,IDN,Indonesia,IDN.21_1,NusaTenggaraTimur,NA,Alor,NA,NA,Kabupaten,Regency,5307,ID.NT.AL,"MULTIPOLYGON (((124.1022 -8.5444, 124.0854 -8...."
1,IDN.21.2_1,IDN,Indonesia,IDN.21_1,NusaTenggaraTimur,NA,Belu,NA,NA,Kabupaten,Regency,5306,ID.NT.BE,"MULTIPOLYGON (((124.8313 -9.7605, 124.824 -9.7..."
2,IDN.21.3_1,IDN,Indonesia,IDN.21_1,NusaTenggaraTimur,NA,Ende,NA,NA,Kabupaten,Regency,5311,ID.NT.EN,"MULTIPOLYGON (((121.5289 -8.8984, 121.528 -8.9..."
3,IDN.21.4_1,IDN,Indonesia,IDN.21_1,NusaTenggaraTimur,NA,FloresTimur,NA,NA,Kabupaten,Regency,5309,ID.NT.FT,"MULTIPOLYGON (((122.7523 -8.6048, 122.7473 -8...."
4,IDN.21.5_1,IDN,Indonesia,IDN.21_1,NusaTenggaraTimur,NA,KotaKupang,NA,NA,Kota,City,5371,ID.NT.KM,"MULTIPOLYGON (((123.6247 -10.14, 123.6293 -10...."

In [4]:
gdf['NAME_2'] = gdf['NAME_2'].replace({
    'FloresTimur': 'Flores Timur',
    'ManggaraiBarat': 'Manggarai Barat',
    'ManggaraiTimur': 'Manggarai Timur',
    'KotaKupang': 'Kota Kupang',
    'RoteNdao': 'Rote Ndao',
    'SabuRaijua': 'Sabu Raijua',
    'SumbaBarat': 'Sumba Barat',
    'SumbaBaratDaya': 'Sumba Barat Daya',
    'SumbaTengah': 'Sumba Tengah',
    'SumbaTimur': 'Sumba Timur',
    'TimorTengahSelatan': 'Timor Tengah Selatan',
    'TimorTengahUtara': 'Timor Tengah Utara'
})

In [5]:
gdf.head()

,GID_2,GID_0,COUNTRY,GID_1,NAME_1,NL_NAME_1,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,geometry
0,IDN.21.1_1,IDN,Indonesia,IDN.21_1,NusaTenggaraTimur,NA,Alor,NA,NA,Kabupaten,Regency,5307,ID.NT.AL,"MULTIPOLYGON (((124.1022 -8.5444, 124.0854 -8...."
1,IDN.21.2_1,IDN,Indonesia,IDN.21_1,NusaTenggaraTimur,NA,Belu,NA,NA,Kabupaten,Regency,5306,ID.NT.BE,"MULTIPOLYGON (((124.8313 -9.7605, 124.824 -9.7..."
2,IDN.21.3_1,IDN,Indonesia,IDN.21_1,NusaTenggaraTimur,NA,Ende,NA,NA,Kabupaten,Regency,5311,ID.NT.EN,"MULTIPOLYGON (((121.5289 -8.8984, 121.528 -8.9..."
3,IDN.21.4_1,IDN,Indonesia,IDN.21_1,NusaTenggaraTimur,NA,Flores Timur,NA,NA,Kabupaten,Regency,5309,ID.NT.FT,"MULTIPOLYGON (((122.7523 -8.6048, 122.7473 -8...."
4,IDN.21.5_1,IDN,Indonesia,IDN.21_1,NusaTenggaraTimur,NA,Kota Kupang,NA,NA,Kota,City,5371,ID.NT.KM,"MULTIPOLYGON (((123.6247 -10.14, 123.6293 -10...."

In [6]:
gdf.to_file('ntt.geojson', driver='GeoJSON')