## CHECK DATA

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data_tanah.csv', sep=';')
df.head()

,NO,KABUPATEN,KECAMATAN,ALAMAT LENGKAP,LUAS,PERUNTUKKAN PADA AIW,PEMANFAATAN SAAT INI,NO SERTIFIKAT,TGL SERTIFIKAT,NO AIW,TGL AIW,NAMA WAKIF,NAMA NADZIR,LUAS.1,KOORDINAT,STATUS SERTIFIKAT
0,2,FLORES TIMUR,Adonara Timur,Bilal/Honihama,406 M2,Masjid,Masjid An Nur Honihama,M.5,14/09/92,01/W2/1992,18/02/92,Mustafa Serang,Alias Tena Boli,406,"-8.36529643282978, 123.13694416860255",SUDAH
1,3,FLORES TIMUR,Adonara Timur,Bilal,1.179 M2,Pekuburan Islam,Pekuburan Islam,-,-,AIW/36/1993,20/01/93,Arkian Sili,Ahmad Mamang,1179,"-8.386856514672763, 123.1617282818485",SUDAH
2,5,FLORES TIMUR,Adonara Timur,Waiburak,503 M2,Langgar,Langgar Nurul Yakin,M 102,05/11/92,13/W2/1992,12/W2/1992,Arkiang Kamba key Helo,Muhammad Saleh,503,"-8.386285386086977, 123.17184934925551",SUDAH
3,6,FLORES TIMUR,Adonara Timur,Waiburak/Belle,703 M2,Masjid,Masjid Al-Kalam Belle,M 166,25/02/94,AIW/46/1993,20/01/93,Kadir kopong Duran,Arifin Tokan,703,"-8.383813702798111, 123.1776068061002",SUDAH
4,10,FLORES TIMUR,Adonara Timur,Lamahala Jaya,313 M2,Mushollah,Mushollah Suluk,1,07/01/19,W2/1/001/III/2015,19/03/15,Abubakar Sidik Bethan,Abubakar Sidik Bethan,313,"-8.38928382687744, 123.15338720516638",SUDAH

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   NO                    104 non-null    int64
 1   KABUPATEN             104 non-null    object
 2   KECAMATAN             104 non-null    object
 3   ALAMAT LENGKAP        102 non-null    object
 4   LUAS                  99 non-null     object
 5   PERUNTUKKAN PADA AIW  94 non-null     object
 6   PEMANFAATAN SAAT INI  99 non-null     object
 7   NO SERTIFIKAT         84 non-null     object
 8   TGL SERTIFIKAT        83 non-null     object
 9   NO AIW                80 non-null     object
 10  TGL AIW               77 non-null     object
 11  NAMA WAKIF            90 non-null     object
 12  NAMA NADZIR           91 non-null     object
 13  LUAS.1                104 non-null    int64
 14  KOORDINAT             104 non-null    object
 15  STATUS SERTIFIKAT     104 non-null    object
dtypes: int64(2), object(14)
memory usage: 13.1+ KB

In [4]:
df = df.drop(columns=['LUAS'])
df = df.rename(columns={'LUAS.1': 'LUAS'})

In [5]:
df = df.drop(columns=['NO'])

In [6]:
df

,KABUPATEN,KECAMATAN,ALAMAT LENGKAP,PERUNTUKKAN PADA AIW,PEMANFAATAN SAAT INI,NO SERTIFIKAT,TGL SERTIFIKAT,NO AIW,TGL AIW,NAMA WAKIF,NAMA NADZIR,LUAS,KOORDINAT,STATUS SERTIFIKAT
0,FLORES TIMUR,Adonara Timur,Bilal/Honihama,Masjid,Masjid An Nur Honihama,M.5,14/09/92,01/W2/1992,18/02/92,Mustafa Serang,Alias Tena Boli,406,"-8.36529643282978, 123.13694416860255",SUDAH
1,FLORES TIMUR,Adonara Timur,Bilal,Pekuburan Islam,Pekuburan Islam,-,-,AIW/36/1993,20/01/93,Arkian Sili,Ahmad Mamang,1179,"-8.386856514672763, 123.1617282818485",SUDAH
2,FLORES TIMUR,Adonara Timur,Waiburak,Langgar,Langgar Nurul Yakin,M 102,05/11/92,13/W2/1992,12/W2/1992,Arkiang Kamba key Helo,Muhammad Saleh,503,"-8.386285386086977, 123.17184934925551",SUDAH
3,FLORES TIMUR,Adonara Timur,Waiburak/Belle,Masjid,Masjid Al-Kalam Belle,M 166,25/02/94,AIW/46/1993,20/01/93,Kadir kopong Duran,Arifin Tokan,703,"-8.383813702798111, 123.1776068061002",SUDAH
4,FLORES TIMUR,Adonara Timur,Lamahala Jaya,Mushollah,Mushollah Suluk,1,07/01/19,W2/1/001/III/2015,19/03/15,Abubakar Sidik Bethan,Abubakar Sidik Bethan,313,"-8.38928382687744, 123.15338720516638",SUDAH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,Manggarai Timur,Borong,Rana Loba,Masjid Nurul Jihad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1840,"-5.428114462719312, 120.38547683460902",BELUM
100,Manggarai Timur,Borong,Rana Loba,Pekuburan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3030,"-5.431630235663989, 120.3802351220944",BELUM
101,Manggarai Timur,Borong,Kota Ndora,Masjid Baiturrahman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1064,"-8.81861925658038, 120.6134894784696",BELUM
102,Manggarai Timur,Borong,Nanga Labang,Masjid Muhajirin Cepi Watu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,624,"-8.813000245791526, 120.58911929352716",BELUM
103,Manggarai Timur,Lamba Leda,Waso / Satar Padut,Masjid Baburrahman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,562,"-8.300256496949391, 120.55841196283677",BELUM

### REKAP SEDERHANA

In [7]:
kabupaten = df['KABUPATEN'].unique()
rekap_df = pd.DataFrame(columns=['KABUPATEN', 'JUMLAH BIDANG', 'TOTAL LUAS (M2)', 'SUDAH BERSERTIFIKAT', 'BELUM BERSERTIFIKAT', 'PERSENTASE (%)'])
rekap_df['KABUPATEN'] = kabupaten
rekap_df['KABUPATEN'] = rekap_df['KABUPATEN'].replace('KAB.KUPANG', 'Kupang')
rekap_df['KABUPATEN'] = rekap_df['KABUPATEN'].replace('KAB. SIKKA', 'Sikka')

In [8]:
counts = []
for kab in kabupaten:
    count = df[df['KABUPATEN'] == kab].shape[0]
    counts.append(count)

rekap_df['JUMLAH BIDANG'] = counts

In [9]:
luas = []
for kab in kabupaten:
    total_luas = df[df['KABUPATEN'] == kab]['LUAS'].sum()
    luas.append(f"{total_luas}")
rekap_df['TOTAL LUAS (M2)'] = luas

In [10]:
sudah_sertifikat = []
for kab in kabupaten:
    count = df[(df['KABUPATEN'] == kab) & (df['STATUS SERTIFIKAT'] == 'SUDAH')].shape[0]
    sudah_sertifikat.append(count)
rekap_df['SUDAH BERSERTIFIKAT'] = sudah_sertifikat

In [11]:
belum_sertifikat = []
for kab in kabupaten:
    count = df[(df['KABUPATEN'] == kab) & (df['STATUS SERTIFIKAT'] == 'BELUM')].shape[0]
    belum_sertifikat.append(count)
rekap_df['BELUM BERSERTIFIKAT'] = belum_sertifikat

In [12]:
persentase = []
for i in range(len(rekap_df)):
    if rekap_df.loc[i, 'JUMLAH BIDANG'] > 0:
        persentase_value = (rekap_df.loc[i, 'SUDAH BERSERTIFIKAT'] / rekap_df.loc[i, 'JUMLAH BIDANG'])
    else:
        persentase_value = 0
    persentase.append(f"{persentase_value:.2f}")
rekap_df['PERSENTASE (%)'] = persentase

In [13]:
rekap_df['KABUPATEN'] = rekap_df['KABUPATEN'].str.title()
df['KABUPATEN'] = df['KABUPATEN'].str.title()

In [14]:
rekap_df

,KABUPATEN,JUMLAH BIDANG,TOTAL LUAS (M2),SUDAH BERSERTIFIKAT,BELUM BERSERTIFIKAT,PERSENTASE (%)
0,Flores Timur,23,32035,22,1,0.96
1,Sumba Timur,11,29635,11,0,1.00
2,Sumba Barat,5,8398,0,5,0.00
3,Alor,6,5630,0,6,0.00
4,Sabu Raijua,1,2035,0,1,0.00
5,Malaka,5,8050,5,0,1.00
6,Kupang,6,15267,0,6,0.00
7,Nagekeo,4,2775,0,4,0.00
8,Sikka,5,3811,0,5,0.00
9,Ende,26,8574,0,26,0.00
10,Manggarai Barat,1,1408,0,1,0.00
11,Kota Kupang,5,1587,0,5,0.00
12,Ngada,1,0,0,1,0.00
13,Manggarai Timur,5,7120,0,5,0.00

In [59]:
rekap_df.to_json('rekap_kab.json', orient='records', force_ascii=False)

## REKAP PER TANAH

In [15]:
df.head()

,KABUPATEN,KECAMATAN,ALAMAT LENGKAP,PERUNTUKKAN PADA AIW,PEMANFAATAN SAAT INI,NO SERTIFIKAT,TGL SERTIFIKAT,NO AIW,TGL AIW,NAMA WAKIF,NAMA NADZIR,LUAS,KOORDINAT,STATUS SERTIFIKAT
0,Flores Timur,Adonara Timur,Bilal/Honihama,Masjid,Masjid An Nur Honihama,M.5,14/09/92,01/W2/1992,18/02/92,Mustafa Serang,Alias Tena Boli,406,"-8.36529643282978, 123.13694416860255",SUDAH
1,Flores Timur,Adonara Timur,Bilal,Pekuburan Islam,Pekuburan Islam,-,-,AIW/36/1993,20/01/93,Arkian Sili,Ahmad Mamang,1179,"-8.386856514672763, 123.1617282818485",SUDAH
2,Flores Timur,Adonara Timur,Waiburak,Langgar,Langgar Nurul Yakin,M 102,05/11/92,13/W2/1992,12/W2/1992,Arkiang Kamba key Helo,Muhammad Saleh,503,"-8.386285386086977, 123.17184934925551",SUDAH
3,Flores Timur,Adonara Timur,Waiburak/Belle,Masjid,Masjid Al-Kalam Belle,M 166,25/02/94,AIW/46/1993,20/01/93,Kadir kopong Duran,Arifin Tokan,703,"-8.383813702798111, 123.1776068061002",SUDAH
4,Flores Timur,Adonara Timur,Lamahala Jaya,Mushollah,Mushollah Suluk,1,07/01/19,W2/1/001/III/2015,19/03/15,Abubakar Sidik Bethan,Abubakar Sidik Bethan,313,"-8.38928382687744, 123.15338720516638",SUDAH

In [16]:
df

,KABUPATEN,KECAMATAN,ALAMAT LENGKAP,PERUNTUKKAN PADA AIW,PEMANFAATAN SAAT INI,NO SERTIFIKAT,TGL SERTIFIKAT,NO AIW,TGL AIW,NAMA WAKIF,NAMA NADZIR,LUAS,KOORDINAT,STATUS SERTIFIKAT
0,Flores Timur,Adonara Timur,Bilal/Honihama,Masjid,Masjid An Nur Honihama,M.5,14/09/92,01/W2/1992,18/02/92,Mustafa Serang,Alias Tena Boli,406,"-8.36529643282978, 123.13694416860255",SUDAH
1,Flores Timur,Adonara Timur,Bilal,Pekuburan Islam,Pekuburan Islam,-,-,AIW/36/1993,20/01/93,Arkian Sili,Ahmad Mamang,1179,"-8.386856514672763, 123.1617282818485",SUDAH
2,Flores Timur,Adonara Timur,Waiburak,Langgar,Langgar Nurul Yakin,M 102,05/11/92,13/W2/1992,12/W2/1992,Arkiang Kamba key Helo,Muhammad Saleh,503,"-8.386285386086977, 123.17184934925551",SUDAH
3,Flores Timur,Adonara Timur,Waiburak/Belle,Masjid,Masjid Al-Kalam Belle,M 166,25/02/94,AIW/46/1993,20/01/93,Kadir kopong Duran,Arifin Tokan,703,"-8.383813702798111, 123.1776068061002",SUDAH
4,Flores Timur,Adonara Timur,Lamahala Jaya,Mushollah,Mushollah Suluk,1,07/01/19,W2/1/001/III/2015,19/03/15,Abubakar Sidik Bethan,Abubakar Sidik Bethan,313,"-8.38928382687744, 123.15338720516638",SUDAH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,Manggarai Timur,Borong,Rana Loba,Masjid Nurul Jihad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1840,"-5.428114462719312, 120.38547683460902",BELUM
100,Manggarai Timur,Borong,Rana Loba,Pekuburan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3030,"-5.431630235663989, 120.3802351220944",BELUM
101,Manggarai Timur,Borong,Kota Ndora,Masjid Baiturrahman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1064,"-8.81861925658038, 120.6134894784696",BELUM
102,Manggarai Timur,Borong,Nanga Labang,Masjid Muhajirin Cepi Watu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,624,"-8.813000245791526, 120.58911929352716",BELUM
103,Manggarai Timur,Lamba Leda,Waso / Satar Padut,Masjid Baburrahman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,562,"-8.300256496949391, 120.55841196283677",BELUM

In [17]:
df['PERUNTUKKAN PADA AIW'].unique()

array(['Masjid', 'Pekuburan Islam', 'Langgar', 'Mushollah', 'Pemakaman',
       'Sekolah', 'Kuburan Islam', 'PEKUBURAN', 'MASJID', 'MADRASAH',
       'KEBUN', 'Mushola', 'Masjid Al Jihad Betun',
       'Masjid Al Qadr Betun', 'Kuburan Islam I Betun',
       'Masjid Al Falah Kletek', 'Kemaslahatan Ummat', nan,
       'MASJID NURUL HUDA', 'Makam', 'Mushalla Quba',
       'Mushalla Al-Mujahidin', 'Masjid Nurul Huda', 'Masjid Nur Hidayah',
       'Mushalla Nur Hasanah', 'Masjid At Taqwa', 'Masjid Al-Mujahidin',
       'Masjid Nurul Iman', 'Poliklinik Bersalin Muhammadiyah',
       'Masjid Abubekar Sidiq', 'Masjid Mujjahiddin', 'Masjid Qilblatain',
       'Masjid Attaqwa Nur Al Anshar', 'Masjid Al-Fatah',
       'Masjid Arrahman', "Masjid Baitul Ma'mur", 'Masjid Allahu Akbar',
       "Masjid Al-A'raf", 'Masjid Nur Ilahi', 'Masjid Ar Rahman',
       'Masjid Jami Taqwa', 'Masjid Nurul Hidayah', 'Masjid Nurul Jihad',
       'Pekuburan', 'Masjid Baiturrahman', 'Masjid Muhajirin Cepi Watu',
       'Masjid Baburrahman'], dtype=object)

In [18]:
kat_mushalla = ['Langgar', 'Mushalla', 'Musala', 'Musollah', 'Mushola', 'Musholla', 'Musholah', 'Langgar/ Mushalla', 'Langgar/Mushalla', 'Langgar/Mushola', 'Langgar/Musholla', 'Langgar/Musala', 'Langgar/Musollah', 'Langgar/Musollah', 'Langgar/Musolah']
kat_masjid = ['Masjid', 'Masjid Jami', 'Masjid Jami\'', 'Masjid Raya', 'Masjid Agung']
kat_sekolah = ['Sekolah', 'Madrasah', 'Pesantren', 'Pondok Pesantren', 'Pondok Pesantren/Madrasah', 'Pesantren/Madrasah']
kat_makam = ['Perkuburan', 'Perkuburan Islam' , 'Kuburan', 'Makam', 'Makam Islam', 'Makam/Kuburan', 'Makam/Perkuburan', 'Kuburan/Makam', 'Kuburan/Perkuburan', 'Perkuburan/Makam', 'Perkuburan/Kuburan']
kat_hijau = ['Kebun', 'Taman', 'RTH', 'Ruang Terbuka Hijau', 'RTH/Taman', 'Taman/RTH']
def categorize_peruntukkan(value):
    if pd.isna(value):
        return 'Lainnya'
    value = value.strip().lower()
    if any(kat.lower() in value for kat in kat_mushalla):
        return 'Mushalla'
    elif any(kat.lower() in value for kat in kat_masjid):
        return 'Masjid'
    elif any(kat.lower() in value for kat in kat_sekolah):
        return 'Sekolah'
    elif any(kat.lower() in value for kat in kat_makam):
        return 'Makam'
    elif any(kat.lower() in value for kat in kat_hijau):
        return 'Ruang Terbuka Hijau'
    else:
        return 'Kemaslahatan Umat'
    
df['KATEGORI'] = df['PERUNTUKKAN PADA AIW'].apply(categorize_peruntukkan)

In [19]:
df['PEMANFAATAN SAAT INI'] = df['PEMANFAATAN SAAT INI'].fillna(df['PERUNTUKKAN PADA AIW'])

In [20]:
df['PERUNTUKKAN PADA AIW'] = df['PERUNTUKKAN PADA AIW'].fillna('Masjid')

In [21]:
df = df.fillna('-')

In [22]:
df['KABUPATEN'] = [kab.upper() for kab in df['KABUPATEN']]

In [23]:
df

,KABUPATEN,KECAMATAN,ALAMAT LENGKAP,PERUNTUKKAN PADA AIW,PEMANFAATAN SAAT INI,NO SERTIFIKAT,TGL SERTIFIKAT,NO AIW,TGL AIW,NAMA WAKIF,NAMA NADZIR,LUAS,KOORDINAT,STATUS SERTIFIKAT,KATEGORI
0,FLORES TIMUR,Adonara Timur,Bilal/Honihama,Masjid,Masjid An Nur Honihama,M.5,14/09/92,01/W2/1992,18/02/92,Mustafa Serang,Alias Tena Boli,406,"-8.36529643282978, 123.13694416860255",SUDAH,Masjid
1,FLORES TIMUR,Adonara Timur,Bilal,Pekuburan Islam,Pekuburan Islam,-,-,AIW/36/1993,20/01/93,Arkian Sili,Ahmad Mamang,1179,"-8.386856514672763, 123.1617282818485",SUDAH,Makam
2,FLORES TIMUR,Adonara Timur,Waiburak,Langgar,Langgar Nurul Yakin,M 102,05/11/92,13/W2/1992,12/W2/1992,Arkiang Kamba key Helo,Muhammad Saleh,503,"-8.386285386086977, 123.17184934925551",SUDAH,Mushalla
3,FLORES TIMUR,Adonara Timur,Waiburak/Belle,Masjid,Masjid Al-Kalam Belle,M 166,25/02/94,AIW/46/1993,20/01/93,Kadir kopong Duran,Arifin Tokan,703,"-8.383813702798111, 123.1776068061002",SUDAH,Masjid
4,FLORES TIMUR,Adonara Timur,Lamahala Jaya,Mushollah,Mushollah Suluk,1,07/01/19,W2/1/001/III/2015,19/03/15,Abubakar Sidik Bethan,Abubakar Sidik Bethan,313,"-8.38928382687744, 123.15338720516638",SUDAH,Mushalla
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,MANGGARAI TIMUR,Borong,Rana Loba,Masjid Nurul Jihad,Masjid Nurul Jihad,-,-,-,-,-,-,1840,"-5.428114462719312, 120.38547683460902",BELUM,Masjid
100,MANGGARAI TIMUR,Borong,Rana Loba,Pekuburan,Pekuburan,-,-,-,-,-,-,3030,"-5.431630235663989, 120.3802351220944",BELUM,Makam
101,MANGGARAI TIMUR,Borong,Kota Ndora,Masjid Baiturrahman,Masjid Baiturrahman,-,-,-,-,-,-,1064,"-8.81861925658038, 120.6134894784696",BELUM,Masjid
102,MANGGARAI TIMUR,Borong,Nanga Labang,Masjid Muhajirin Cepi Watu,Masjid Muhajirin Cepi Watu,-,-,-,-,-,-,624,"-8.813000245791526, 120.58911929352716",BELUM,Masjid
103,MANGGARAI TIMUR,Lamba Leda,Waso / Satar Padut,Masjid Baburrahman,Masjid Baburrahman,-,-,-,-,-,-,562,"-8.300256496949391, 120.55841196283677",BELUM,Masjid

In [24]:
df['KATEGORI'].unique()

array(['Masjid', 'Makam', 'Mushalla', 'Sekolah', 'Ruang Terbuka Hijau',
       'Kemaslahatan Umat', 'Lainnya'], dtype=object)

In [25]:
df['KABUPATEN'] = df['KABUPATEN'].str.title()
rekap_df['KABUPATEN'] = rekap_df['KABUPATEN'].str.title()

In [26]:
df.columns = [col.lower().replace(' ', '_') for col in df.columns]
df = df.rename(columns={'koordinat': 'coordinate'})
rekap_df.columns = [col.lower().replace(' ', '_') for col in rekap_df.columns]

In [27]:
df.head()

,kabupaten,kecamatan,alamat_lengkap,peruntukkan_pada_aiw,pemanfaatan_saat_ini,no_sertifikat,tgl_sertifikat,no_aiw,tgl_aiw,nama_wakif,nama_nadzir,luas,coordinate,status_sertifikat,kategori
0,Flores Timur,Adonara Timur,Bilal/Honihama,Masjid,Masjid An Nur Honihama,M.5,14/09/92,01/W2/1992,18/02/92,Mustafa Serang,Alias Tena Boli,406,"-8.36529643282978, 123.13694416860255",SUDAH,Masjid
1,Flores Timur,Adonara Timur,Bilal,Pekuburan Islam,Pekuburan Islam,-,-,AIW/36/1993,20/01/93,Arkian Sili,Ahmad Mamang,1179,"-8.386856514672763, 123.1617282818485",SUDAH,Makam
2,Flores Timur,Adonara Timur,Waiburak,Langgar,Langgar Nurul Yakin,M 102,05/11/92,13/W2/1992,12/W2/1992,Arkiang Kamba key Helo,Muhammad Saleh,503,"-8.386285386086977, 123.17184934925551",SUDAH,Mushalla
3,Flores Timur,Adonara Timur,Waiburak/Belle,Masjid,Masjid Al-Kalam Belle,M 166,25/02/94,AIW/46/1993,20/01/93,Kadir kopong Duran,Arifin Tokan,703,"-8.383813702798111, 123.1776068061002",SUDAH,Masjid
4,Flores Timur,Adonara Timur,Lamahala Jaya,Mushollah,Mushollah Suluk,1,07/01/19,W2/1/001/III/2015,19/03/15,Abubakar Sidik Bethan,Abubakar Sidik Bethan,313,"-8.38928382687744, 123.15338720516638",SUDAH,Mushalla

In [28]:
df['kabupaten'] = [kab if kab != 'Kab. Sikka' else 'Sikka' for kab in df['kabupaten']]

In [29]:
df['kabupaten'] = [kab if kab != 'Kab.Kupang' else 'Kupang' for kab in df['kabupaten']]

In [30]:
df['kabupaten'].unique()

array(['Flores Timur', 'Sumba Timur', 'Sumba Barat', 'Alor',
       'Sabu Raijua', 'Malaka', 'Kupang', 'Nagekeo', 'Sikka', 'Ende',
       'Manggarai Barat', 'Kota Kupang', 'Ngada', 'Manggarai Timur'],
      dtype=object)

In [105]:
df.to_csv('data_tanah_cleaned.csv', sep=';', index=False)

In [106]:
df.to_json('data_tanah_cleaned.json', orient='records', force_ascii=False)

### EXPORT TO GPX

In [32]:
df

,kabupaten,kecamatan,alamat_lengkap,peruntukkan_pada_aiw,pemanfaatan_saat_ini,no_sertifikat,tgl_sertifikat,no_aiw,tgl_aiw,nama_wakif,nama_nadzir,luas,coordinate,status_sertifikat,kategori
0,Flores Timur,Adonara Timur,Bilal/Honihama,Masjid,Masjid An Nur Honihama,M.5,14/09/92,01/W2/1992,18/02/92,Mustafa Serang,Alias Tena Boli,406,"-8.36529643282978, 123.13694416860255",SUDAH,Masjid
1,Flores Timur,Adonara Timur,Bilal,Pekuburan Islam,Pekuburan Islam,-,-,AIW/36/1993,20/01/93,Arkian Sili,Ahmad Mamang,1179,"-8.386856514672763, 123.1617282818485",SUDAH,Makam
2,Flores Timur,Adonara Timur,Waiburak,Langgar,Langgar Nurul Yakin,M 102,05/11/92,13/W2/1992,12/W2/1992,Arkiang Kamba key Helo,Muhammad Saleh,503,"-8.386285386086977, 123.17184934925551",SUDAH,Mushalla
3,Flores Timur,Adonara Timur,Waiburak/Belle,Masjid,Masjid Al-Kalam Belle,M 166,25/02/94,AIW/46/1993,20/01/93,Kadir kopong Duran,Arifin Tokan,703,"-8.383813702798111, 123.1776068061002",SUDAH,Masjid
4,Flores Timur,Adonara Timur,Lamahala Jaya,Mushollah,Mushollah Suluk,1,07/01/19,W2/1/001/III/2015,19/03/15,Abubakar Sidik Bethan,Abubakar Sidik Bethan,313,"-8.38928382687744, 123.15338720516638",SUDAH,Mushalla
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,Manggarai Timur,Borong,Rana Loba,Masjid Nurul Jihad,Masjid Nurul Jihad,-,-,-,-,-,-,1840,"-5.428114462719312, 120.38547683460902",BELUM,Masjid
100,Manggarai Timur,Borong,Rana Loba,Pekuburan,Pekuburan,-,-,-,-,-,-,3030,"-5.431630235663989, 120.3802351220944",BELUM,Makam
101,Manggarai Timur,Borong,Kota Ndora,Masjid Baiturrahman,Masjid Baiturrahman,-,-,-,-,-,-,1064,"-8.81861925658038, 120.6134894784696",BELUM,Masjid
102,Manggarai Timur,Borong,Nanga Labang,Masjid Muhajirin Cepi Watu,Masjid Muhajirin Cepi Watu,-,-,-,-,-,-,624,"-8.813000245791526, 120.58911929352716",BELUM,Masjid
103,Manggarai Timur,Lamba Leda,Waso / Satar Padut,Masjid Baburrahman,Masjid Baburrahman,-,-,-,-,-,-,562,"-8.300256496949391, 120.55841196283677",BELUM,Masjid

In [35]:
df_gpx = df[['kabupaten','pemanfaatan_saat_ini', 'coordinate']]
df_gpx = df_gpx[df_gpx['kabupaten'] ==  'Kota Kupang']
df_gpx = df_gpx.rename(columns={'pemanfaatan_saat_ini': 'name'})
df_gpx['latitude'] = df_gpx['coordinate'].apply(lambda x: float(x.split(',')[0]) if pd.notna(x) and ',' in x else None)
df_gpx['longitude'] = df_gpx['coordinate'].apply(lambda x: float(x.split(',')[1]) if pd.notna(x) and ',' in x else None)
df_gpx = df_gpx.drop(columns=['coordinate'])
df_gpx = df_gpx.dropna(subset=['latitude', 'longitude'])

In [36]:
df_gpx.head()

      kabupaten                   name   latitude   longitude
93  Kota Kupang   Masjid/Tempat Ibadah -10.146697  123.649367
94  Kota Kupang  Al Islah Al Islamiyah -10.139754  123.668095
95  Kota Kupang      Masjid Baburahman -10.161736  123.615268
96  Kota Kupang        Masjid At Taqwa -10.178940  123.598823
97  Kota Kupang                 Masjid -10.195715  123.624583

In [38]:
import gpxpy
import gpxpy.gpx

# Create GPX object
gpx = gpxpy.gpx.GPX()

# Create a GPX track
track = gpxpy.gpx.GPXTrack()
gpx.tracks.append(track)

# Create a segment in the track
segment = gpxpy.gpx.GPXTrackSegment()
track.segments.append(segment)

# Loop through DataFrame rows and add points
for _, row in df_gpx.iterrows():
    point = gpxpy.gpx.GPXTrackPoint(
        latitude=row['latitude'],
        longitude=row['longitude'],
        name=row.get('name', None)
    )
    segment.points.append(point)

# Save to file
with open('kota_kupang.gpx', 'w') as f:
    f.write(gpx.to_xml())

print("✅ GPX file created: output.gpx")

✅ GPX file created: output.gpx